version: '3.7'
services:
  web:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./nginx:/var/log/nginx
    networks:
      - nginx-ssl
    ports:
      - "60000:80"
    environment:
      TZ: "Asia/Tokyo"
      VIRTUAL_HOST: licle.k12i.space
      VIRTUAL_PORT: 60000
      LETSENCRYPT_HOST: licle.k12i.space
      LETSENCRYPT_EMAIL: kazuki.k.bl8@gmail.com

networks:
  nginx-ssl:
    external: true
